# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-20 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorbot', '0002_question_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='detail',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='answer',
            name='source',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=10000),
        ),
    ]
