# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-20 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorbot', '0003_auto_20180720_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='summary',
            field=models.CharField(max_length=500),
        ),
    ]
