# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-20 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorbot', '0004_auto_20180720_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='source',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='answer',
            name='summary',
            field=models.CharField(max_length=1000),
        ),
    ]
