# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-20 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorbot', '0005_auto_20180720_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='detail',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='answer',
            name='source',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='answer',
            name='summary',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(max_length=10000),
        ),
    ]
